name: .conda
channels:
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=22.1.0
  - aws-c-common=0.6.8
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.11
  - aws-sdk-cpp=1.8.185
  - blas=1.0
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.6
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cycler=0.11.0
  - datasets=2.12.0
  - dill=0.3.6
  - et_xmlfile=1.1.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.4.0
  - future=0.18.3
  - gflags=2.2.2
  - giflib=5.2.1
  - glog=0.5.0
  - grpc-cpp=1.46.1
  - huggingface_hub=0.14.1
  - icu=68.1
  - idna=3.4
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libthrift=0.13.0
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - multidict=6.0.2
  - multiprocess=0.70.14
  - munkres=1.1.4
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openai=0.27.4
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.0
  - pandas=1.5.3
  - pandas-stubs=1.5.3.230203
  - pillow=9.4.0
  - pip=23.0.1
  - plotly=5.9.0
  - pooch=1.4.0
  - pyarrow=11.0.0
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - python-xxhash=2.0.2
  - pytz=2022.7
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2022.7.9
  - requests=2.29.0
  - responses=0.13.3
  - sacremoses=0.0.43
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=67.8.0
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.9
  - sqlite=3.41.2
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tokenizers=0.11.4
  - tqdm=4.65.0
  - transformers=4.29.2
  - types-pytz=2022.4.0.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.16
  - utf8proc=2.6.1
  - wheel=0.38.4
  - xxhash=0.8.0
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - anyio==3.7.0
      - argparse==1.4.0
      - backoff==2.2.1
      - cfgv==3.3.1
      - chromadb==0.3.21
      - clickhouse-connect==0.6.1
      - diskcache==5.6.1
      - distlib==0.3.6
      - duckdb==0.8.0
      - exceptiongroup==1.1.1
      - fastapi==0.96.0
      - filelock==3.12.0
      - gtts==2.2.2
      - h11==0.14.0
      - hnswlib==0.7.0
      - httptools==0.5.0
      - identify==2.5.24
      - jinja2==3.1.2
      - llama-cpp-python==0.1.59
      - lz4==4.3.2
      - markupsafe==2.1.3
      - monotonic==1.6
      - mpmath==1.3.0
      - networkx==3.1
      - nltk==3.8.1
      - nodeenv==1.8.0
      - platformdirs==3.5.1
      - posthog==3.0.1
      - pre-commit==3.3.2
      - pydantic==1.10.9
      - pydub==0.25.1
      - python-dotenv==1.0.0
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - simpleaudio==1.0.4
      - sniffio==1.3.0
      - starlette==0.27.0
      - sympy==1.12
      - tiktoken==0.3.3
      - torch==2.0.1
      - torchvision==0.15.2
      - uvicorn==0.22.0
      - uvloop==0.17.0
      - virtualenv==20.23.0
      - watchfiles==0.19.0
      - websockets==11.0.3
      - zstandard==0.21.0
